### PR TITLE
WIP: Parametric closures

### PR DESCRIPTION
**Pull request by cstjean**
Hi @timholy, 

Following the [discussion](https://groups.google.com/forum/#!topic/julia-users/Sbn9FQxXprY) on julia-users, I decided to try out the approach I mentioned: creating parametric types with `@eval` at macro-expansion time. There's no code change in this PR so far, just an attached notebook in HTML format. The code is a lot faster for small values of `n` because it doesn't create a new type at every call. Do you see any problem with that approach? Do you think it's worth making a PR out of it given Jeff's work?

### CODE REVIEW

**Comment by cstjean** [comment]
I looked into reusing some of the existing `getclosure` code, but since we don't need generated functions anymore, the new code is a lot simpler. Was there any particular reason to use `type` instead of `immutable`?

**Comment by malmaud** [comment]
This package is likely going to be obsolete soon since its functionality is being folded into base Julia (see https://github.com/JuliaLang/julia/tree/jb/function). Thus it's probably not worth spending much time on this.

**Comment by timholy** [comment]
Do you see anything wrong with merging this, though? I haven't had time for a detailed review, but a cursory glance looks promising.

Realistically, I wouldn't be surprised if julia 0.5 were not 3-4 months away.

**Comment by malmaud** [comment]
It seems fine to me.

**Comment by timholy** [comment]
Let's do it. Nice work, @cstjean!

**Pull request merged**
